DROP TABLE IF EXISTS ROLE;

CREATE TABLE ROLE (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	"TYPE" VARCHAR(64) DEFAULT NULL,
	DESCRIPTION VARCHAR(64) DEFAULT NULL
);

DROP TABLE IF EXISTS "USER";
CREATE TABLE "USER" (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	USERNAME VARCHAR(256) DEFAULT NULL,
	EMAIL VARCHAR(256) DEFAULT NULL,
	PASSWORD VARCHAR(256) DEFAULT NULL,
	NEW_PASSWORD VARCHAR(256) DEFAULT NULL,
	CONFIRM_PASSWORD VARCHAR(256) DEFAULT NULL,
	VERIFICATION_TOKEN VARCHAR(256) DEFAULT NULL,
	ENABLED BOOLEAN DEFAULT NULL,
	EMAIL_VERIFIED BOOLEAN DEFAULT NULL,
	ROLE_ID INT DEFAULT NULL
);





